# Use this for the debugging of the osrm images
version: "3"
services:
  osrm-backend-standard:
    image: redy1908/green-way-osrm-standard:v1
    ports:
      - "5005:5000"
  osrm-frontend-standard:
    image: osrm/osrm-frontend
    ports:
      - "9966:9966"
    environment:
      - OSRM_BACKEND=http://localhost:5005
  osrm-backend-elevation:
    image: redy1908/green-way-osrm-elevation:v1
    ports:
      - "5006:5000"
  osrm-frontend-elevation:
    image: osrm/osrm-frontend
    ports:
      - "9967:9966"
    environment:
      - OSRM_BACKEND=http://localhost:5006
