version: "3"
services:
  green-way-osrm-distance:
    image: redy1908/green-way-osrm-distance:v1
    ports:
      - "5000:5000"
  green-way-osrm-duration:
    image: redy1908/green-way-osrm-duration:v1
    ports:
      - "5001:5000"
  green-way-osrm-elevation:
    image: redy1908/green-way-osrm-elevation:v1
    ports:
      - "5002:5000"
  green-way-osrm-standard:
    image: redy1908/green-way-osrm-standard:v1
    ports:
      - "5003:5000"
  osrm-frontend:
    image: osrm/osrm-frontend
    ports:
      - "9966:9966"
    environment:
      - OSRM_BACKEND=http://localhost:5002
