FROM ghcr.io/project-osrm/osrm-backend:v5.27.1

COPY ./data /data
COPY profiles/car-elevation.lua /opt

ENV OSRM_RASTER_SOURCE="../data/sud-italy.asc"
ENV LON_MIN=12.9945
ENV LON_MAX=18.8281
ENV LAT_MIN=38.3821
ENV LAT_MAX=42.9229
ENV NROWS=6630
ENV NCOLS=6008

RUN osrm-extract -p /opt/car-elevation.lua /data/sud-italy.osm.pbf && \
        osrm-partition /data/sud-italy.osrm && \
        osrm-customize /data/sud-italy.osrm;

EXPOSE 5000

CMD osrm-routed --algorithm mld /data/sud-italy.osrm
