FROM ghcr.io/project-osrm/osrm-backend:v5.27.1

COPY ./data /data
COPY profiles/car-elevation.lua /opt

ENV OSRM_RASTER_SOURCE="../data/green-way.asc"
ENV LON_MIN=10
ENV LON_MAX=15
ENV LAT_MIN=40
ENV LAT_MAX=45
ENV NROWS=6000
ENV NCOLS=6000

RUN osrm-extract -p /opt/car-elevation.lua /data/green-way.osm.pbf && \
        osrm-partition /data/green-way.osrm && \
        osrm-customize /data/green-way.osrm;

EXPOSE 5000

CMD osrm-routed --algorithm mld /data/green-way.osrm
