FROM ghcr.io/project-osrm/osrm-backend:v5.27.1

COPY ./data /data
COPY profiles/car-duration.lua /opt

ENV OSRM_FILE=sud-latest

RUN osrm-extract -p /opt/car-duration.lua /data/${OSRM_FILE}.osm.pbf && \
        osrm-partition /data/${OSRM_FILE}.osrm && \
        osrm-customize /data/${OSRM_FILE}.osrm;

EXPOSE 5000

CMD osrm-routed --algorithm mld /data/${OSRM_FILE}.osrm
