# 400 error will be thrown above this limit.
max_locations_per_request: 1000


# CORS header. Should be null for no CORS, '*' for all domains, or an url with
# protocol, domain, and port ('https://api.example.com/'). Default is null.
access_control_allow_origin: "*"

datasets:
  - name: greenway
    path: data/greenWay/
    filename_epsg: 4326  # This is the default value.
    filename_tile_size: 1  # This is the default value.

