server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/realms/GreenWay/protocol/openid-connect/certs
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgis
    username: postgis
    password: postgis
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
    show-sql: false
    database: postgresql
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
osrm:
  lon-min: 13.7  # <- CHANGE
  lon-max: 15.00 # <- CHANGE
  lat-min: 40.5  # <- CHANGE
  lat-max: 41.5  # <- CHANGE
  route-standard-url: http://localhost:5000/route/v1/driving/
  route-elevation-url: http://localhost:5001/route/v1/driving/
  table-elevation-url: http://localhost:5001/table/v1/driving/
opentopodata:
  url: http://localhost:5002/v1/greenway
