server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/GreenWay/protocol/openid-connect/certs
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgis:5432/postgis
    username: postgis
    password: postgis
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
osrm:
  distance:
    url: http://green-way-osrm-distance:5000/route/v1/driving/
  duration:
    url: http://green-way-osrm-duration:5000/route/v1/driving/
  elevation:
    url: http://green-way-osrm-elevation:5000/route/v1/driving/
  standard:
    url: http://green-way-osrm-standard:5000/route/v1/driving/
opentopodata:
  url: http://green-way-opentopodata:5000/v1/greenway?locations=
