server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/GreenWay/protocol/openid-connect/certs
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://green-way-postgis:5432/postgis
    username: postgis
    password: postgis
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
    show-sql: false
    database: postgresql
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
osrm:
  lon-min: 12  # <- CHANGE
  lon-max: 18 # <- CHANGE
  lat-min: 39  # <- CHANGE
  lat-max: 42  # <- CHANGE
  route-standard-url: http://green-way-osrm-standard:5000/route/v1/driving/
  route-elevation-url: http://green-way-osrm-elevation:5000/route/v1/driving/
  table-elevation-url: http://green-way-osrm-elevation:5000/table/v1/driving/